<?php

return array(
    'settings' => array(
        'main' => array(
            'name' => 'Общие',
            'type' => 'main',
            'fields' => array(
                'main_menu' => array(
                    'name' => 'Главное меню',
                    'hint' => 'Меню, которое будет использоваться по умолчанию на всех точках',
                    'field' => array('tag' => 'select', 'object_type' => 'screen', 'js' => 'select-two', 'action' => '?module=screen&action=listSelect'),
                    'default' => null,
                    'required' => true,
                ),
                'royalty' => array(
                    'name' => 'Роялти',
                    'hint' => 'Процент от выручки, получаемый франчайзи системы',
                    'field' => array('tag' => 'input', 'type' => 'text',),
                    'default' => null,
                    'required' => false,
                ),
                'u_id' => array(
                    'name' => 'Идентификаторы отправителя',
                    'hint' => 'Укажите идентификаторы отправителей из настроек Вашего шлюза, или *, чтобы использовать отправителя по умолчнию',
                    'field' => array('tag' => 'textarea'),
                    'default' => null,
                    'required' => false,
                ),
                'sms_id' => array(
                    'name' => 'Идентификатор sms.ru',
                    'hint' => 'Введите значение параметра api_id для вашего аккаунта в сервисе sms.ru',
                    'field' => array('tag' => 'input', 'type' => 'text',),
                    'default' => null,
                    'required' => false,
                ),
            ),
        ),
        'log' => array(
            'name' => 'Логирование',
            'type' => 'log',
            'fields' => array(
                'log_settings' => array(
                    'name' => 'Логирование настроек',
                    'hint' => 'Отвечает за логирование изменений настроек системы',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_shop' => array(
                    'name' => 'Логирование точки',
                    'hint' => 'Отвечает за логирование изменений основных данных точки',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_worker' => array(
                    'name' => 'Логирование работников',
                    'hint' => 'Отвечает за логирование изменений основных данных работников',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_franchisee' => array(
                    'name' => 'Логирование франчайзи',
                    'hint' => 'Отвечает за логирование изменений основных данных франчайзи',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_product' => array(
                    'name' => 'Логирование товара',
                    'hint' => 'Отвечает за логирование изменений основных данных товара',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_ingredient' => array(
                    'name' => 'Логирование ингредиента',
                    'hint' => 'Отвечает за логирование изменений основных данных ингредиента',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_screen' => array(
                    'name' => 'Логирование меню',
                    'hint' => 'Отвечает за логирование изменений меню',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offer' => array(
                    'name' => 'Логирование акции',
                    'hint' => 'Отвечает за логирование изменений основных данных акции',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_productIngredients' => array(
                    'name' => 'Логирование состава товара',
                    'hint' => 'Отвечает за логирование изменений ингредиентов, из которых состоит товар',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_productAdditions' => array(
                    'name' => 'Логирование дополнений товара',
                    'hint' => 'Отвечает за логирование изменений дополнений, доступных для товара',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offerWeekdays' => array(
                    'name' => 'Логирование дней недели действия акции',
                    'hint' => 'Отвечает за логирование изменений дней недели, в которые действует акция',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offerDates' => array(
                    'name' => 'Логирование дней года действия акции',
                    'hint' => 'Отвечает за логирование изменений дней года, в которые действует акция',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offerContactGroup' => array(
                    'name' => 'Логирование групп пользователей акции',
                    'hint' => 'Отвечает за логирование изменений доступных для акции групп пользователей',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offerExceptions' => array(
                    'name' => 'Логирование ограничений акции',
                    'hint' => 'Отвечает за логирование изменений заблокированных акций',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offerConditionItems' => array(
                    'name' => 'Логирование условий акции',
                    'hint' => 'Отвечает за логирование изменений условий действия акции',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_motivation' => array(
                    'name' => 'Логирование мотивации',
                    'hint' => 'Отвечает за логирование изменений основных данных мотивации',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_productSku' => array(
                    'name' => 'Логирование артикула',
                    'hint' => 'Отвечает за логирование изменений артикулов товаров',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_offerProfitItems' => array(
                    'name' => 'Логирование бонусов акции',
                    'hint' => 'Отвечает за логирование изменений бонусов акции',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_set' => array(
                    'name' => 'Логирование списков товаров',
                    'hint' => 'Отвечает за логирование изменений основных данных списков товаров',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_supplier' => array(
                    'name' => 'Логирование поставщиков',
                    'hint' => 'Отвечает за логирование изменений основных данных поставщиков',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_ingredientCategory' => array(
                    'name' => 'Логирование категорий ингредиентов',
                    'hint' => 'Отвечает за логирование изменений основных данных категорий ингредиентов',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_categoryIngredients' => array(
                    'name' => 'Логирование наличия ингредиентов в категориях',
                    'hint' => 'Отвечает за логирование изменений наличия ингредиентов в категориях',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_supplierIngredients' => array(
                    'name' => 'Логирование ингредиентов поставщиков',
                    'hint' => 'Отвечает за логирование изменений предоставляемых поставщиками игредиентов',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_shopMotivations' => array(
                    'name' => 'Логирование мотивация на точке',
                    'hint' => 'Отвечает за логирование изменений доступных на точке мотиваций',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_shopOffers' => array(
                    'name' => 'Логирование акции на точке',
                    'hint' => 'Отвечает за логирование изменений доступных на точке акций',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_motivationItems' => array(
                    'name' => 'Логирование елементов мотивации',
                    'hint' => 'Отвечает за логирование изменений элементов, по которым работает мотивация',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_motivationWeekdays' => array(
                    'name' => 'Логирование дней недели мотивации',
                    'hint' => 'Отвечает за логирование дней недели, в которые работает мотивация',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_motivationDates' => array(
                    'name' => 'Логирование дней мотивации',
                    'hint' => 'Отвечает за логирование дней, в которые работает мотивация',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_motivationPeriod' => array(
                    'name' => 'Логирование периодов мотивации',
                    'hint' => 'Отвечает за логирование периодов, во время которых работает мотивация',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_customer' => array(
                    'name' => 'Логирование клиентов',
                    'hint' => 'Отвечает за логирование изменений основных данных клиентов',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
                'log_shopFranchisees' => array(
                    'name' => 'Логирование точек у франчайзи',
                    'hint' => 'Отвечает за логирование точек, которыми владеет франчайзи',
                    'field' => array('tag' => 'input', 'type' => 'checkbox'),
                    'default' => false,
                ),
            ),
        ),
    ),
    'log_types' => array(
        'shop' => array('id' => 0, 'type' => 'shop', 'cases' => array('точка', 'точки', 'точке', 'точки', 'точкой', 'о точке', 'точки')),
        'product' => array('id' => 1, 'type' => 'product', 'cases' => array('товар', 'товара', 'товару', 'товара', 'товаром', 'о товаре')),
        'ingredient' => array('id' => 2, 'type' => 'ingredient', 'cases' => array('ингредиент', 'ингредиента', 'ингредиенту', 'ингредиента', 'ингредиентом', 'об ингредиенте', 'ингредиенты')),
        'screen' => array('id' => 3, 'type' => 'screen', 'cases' => array('точка', 'экрана', 'экрану', 'экрана', 'экраном', 'об экране')),
        'offer' => array('id' => 4, 'type' => 'offer', 'cases' => array('акция', 'акции', 'акцию', 'акции', 'акцией', 'об акции')),
        'productIngredients' => array('id' => 5, 'type' => 'productIngredients', 'cases' => array('ингредиент товара', 'ингредиента товара', 'ингредиенту товара', 'ингредиента товара', 'ингредиентом товара', 'об ингредиенте товара')),
        'productAdditions' => array('id' => 6, 'type' => 'productAdditions', 'cases' => array('дополнение товара', 'дополнения товара', 'дополнению товара', 'дополнения товара', 'дополнением товара', 'о дополнении товара')),
        'offerWeekdays' => array('id' => 7, 'name' => 'Дни недели действия акции', 'type' => 'offerWeekdays', 'cases' => array('', '', '', '', '', '')),
        'offerExceptions' => array('id' => 30, 'name' => 'Ограничение акций', 'type' => 'offerExceptions', 'cases' => array('', '', '', '', '', '')),
        'offerDates' => array('id' => 8, 'name' => 'Дни действия акции', 'type' => 'offerDates', 'cases' => array('', '', '', '', '', '')),
        'offerContactGroup' => array('id' => 9, 'name' => 'Группы контактов, на которые распространяется акция', 'type' => 'offerContactGroup', 'cases' => array('', '', '', '', '', '')),
        'offerConditionItems' => array('id' => 10, 'name' => 'Товары с которыми работает акция', 'type' => 'offerConditionItems', 'cases' => array('', '', '', '', '', '')),
        'motivation' => array('id' => 11, 'name' => 'Мотивация', 'type' => 'motivation', 'cases' => array('мотивация', 'мотивации', 'мотивации', 'мотивации', 'мотивацией', 'о мотивации', 'мотивации')),
        'productSku' => array('id' => 12, 'type' => 'productSku', 'cases' => array('артикул', 'артикула', 'артикулу', 'артикула', 'артикулом', 'об артикуле')),
        'offerProfitItems' => array('id' => 13, 'name' => 'Товары выступающие в качествк бонусов акции', 'type' => 'offerProfitItems', 'cases' => array('', '', '', '', '', '')),
        'set' => array('id' => 14, 'name' => 'Список товаров', 'type' => 'set', 'cases' => array('список', 'списка', 'списку', 'списка', 'списком', 'о списке')),
        'shopOffers' => array('id' => 15, 'type' => 'shopOffers', 'cases' => array('акция на точке', '', '', '', '', '')),
        'settings' => array('id' => 16, 'type' => 'settings', 'cases' => array('настройка', 'настройки', 'настройку', 'настройки', 'настройкой', 'о настройке')),
        'supplier' => array('id' => 17, 'type' => 'supplier', 'cases' => array('поставщик', 'поставщика', 'поставщику', 'поставщика', 'поставщиком', 'о поставщике')),
        'ingredientCategory' => array('id' => 18, 'name' => 'Категория ингредиентов', 'type' => 'ingredientCategory', 'cases' => array('', '', '', '', '', '')),
        'categoryIngredients' => array('id' => 19, 'name' => 'Наличие игредиентов в категории', 'type' => 'categoryIngredients', 'cases' => array('', '', '', '', '', '')),
        'supplierIngredients' => array('id' => 20, 'type' => 'supplierIngredients', 'cases' => array('игредиент предоставляемый поставщиком', '', '', '', '', '')),
        'shopMotivations' => array('id' => 21, 'type' => 'shopMotivations', 'cases' => array('мотивация на точке', '', '', '', '', '')),
        'worker' => array('id' => 22, 'type' => 'worker', 'cases' => array('работник', '', '', '', '', '')),
        'motivationItems' => array('id' => 23, 'type' => 'motivationItems', 'cases' => array('элемент мотивации', '', '', '', '', '')),
        'motivationWeekdays' => array('id' => 24, 'type' => 'motivationWeekdays', 'cases' => array('день недели действия мотивации', '', '', '', '', '')),
        'motivationDates' => array('id' => 25, 'type' => 'motivationDates', 'cases' => array('день действия мотивации', '', '', '', '', '')),
        'motivationPeriod' => array('id' => 26, 'type' => 'motivationPeriod', 'cases' => array('период действия мотивации', '', '', '', '', '')),
        'customer' => array('id' => 27, 'type' => 'customer', 'cases' => array('клиент', '', '', '', '', '')),
        'franchisee' => array('id' => 28, 'type' => 'franchisee', 'cases' => array('франчайзи', '', '', '', '', '')),
        'shopFranchisees' => array('id' => 29, 'type' => 'shopFranchisees', 'cases' => array('франчайзи с точкой', '', '', '', '', '')),
    ),
    'action_types' => array(
        'create' => array('id' => 1, 'code' => 'create', 'name' => 'создал'),
        'edit' => array('id' => 2, 'code' => 'edit', 'name' => 'отредактировал'),
        'delete' => array('id' => 3, 'code' => 'delete', 'name' => 'удалил'),
        'repair' => array('id' => 4, 'code' => 'repair', 'name' => 'восстановил'),
        'moderation' => array('id' => 5, 'code' => 'moderation', 'name' => 'отправил на модерацию'),
        'off' => array('id' => 6, 'code' => 'off', 'name' => 'отключил'),
        'on' => array('id' => 7, 'code' => 'on', 'name' => 'включил'),
    ),
    'fields' => array(
        'ingredient' => array(
            'name' => array('type' => 'string', 'max_length' => 100, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'code' => array('type' => 'string', 'max_length' => 50, 'min_length' => 4, 'regexp' => '/[^A-Za-z0-9]/', 'name' => 'внутренний код', 'viewed' => true),
            'price' => array('type' => 'decimal', 'min' => 0.01, 'name' => 'цена', 'step' => 0.01, 'viewed' => true),
            'calories' => array('type' => 'decimal', 'min' => 1, 'name' => 'калорийность'),
            'proteins' => array('type' => 'decimal', 'min' => 0, 'name' => 'белки'),
            'fats' => array('type' => 'decimal', 'min' => 0, 'name' => 'жиры'),
            'carbohydrates' => array('type' => 'decimal', 'min' => 0, 'name' => 'углеводы'),
            'dimension' => array('type' => 'config', 'code' => 'dimension', 'name' => 'измерение'),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'inventory' => array(
            'id' => array('name' => 'инвентаризация', 'viewed' => true),
            'shop_name' => array('name' => 'точка', 'viewed' => true),
            'shop_id' => array('type' => 'select-two', 'code' => 'shop_id', 'action' => '?module=backend&action=selectTwo&class=shop', 'name' => 'точка'),
            'type' => array('type' => 'config', 'code' => 'type', 'config' => 'inventory_type', 'name' => 'Тип', 'viewed' => true),
            'date_time' => array('type' => 'time', 'code' => 'date_time', 'name' => 'время инвентаризации', 'format' => 'HH:mm:ss', 'nullable' => true, 'viewed' => true),
            'comment' => array('type' => 'text', 'code' => 'comment', 'max_length' => 5000, 'min_length' => 10, 'name' => 'комментарий'),
        ),
        'order' => array(
            'id' => array('name' => 'заказ', 'viewed' => true),
            'shop_name' => array('name' => 'точка', 'viewed' => true),
            'payment_type' => array('type' => 'config', 'code' => 'payment_type', 'name' => 'тип оплаты'),
            'price' => array('type' => 'decimal', 'name' => 'цена', 'nullable' => true, 'viewed' => true),
            'discount' => array('type' => 'decimal', 'name' => 'скидка', 'nullable' => true),
            'purchase' => array('type' => 'decimal', 'name' => 'себестоимоть', 'nullable' => true),
            'shop_id' => array('type' => 'select-two', 'code' => 'shop_id', 'action' => '?module=backend&action=selectTwo&class=shop', 'name' => 'точка'),
            'date_time' => array('type' => 'time', 'code' => 'date_time', 'name' => 'время оформления', 'format' => 'HH:mm:ss', 'nullable' => true, 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'product' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'price' => array('type' => 'decimal', 'name' => 'цена', 'nullable' => true, 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'addition' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'price' => array('type' => 'decimal', 'name' => 'цена', 'nullable' => true, 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'worker' => array(
            'name' => array('type' => '', 'name' => 'имя', 'max_length' => 90, 'min_length' => 1, 'nullable' => true, 'viewed' => true),
            'salary' => array('type' => 'decimal', 'name' => 'зарплата', 'min' => 0, 'nullable' => true),
            'hour_payment' => array('type' => 'decimal', 'name' => 'ставка', 'min' => 0, 'hint' => 'почасовая оплата', 'nullable' => true),
            'interest_rate' => array('type' => 'decimal', 'name' => 'процентная ставка', 'min' => 0, 'nullable' => true),
            'amount' => array('type' => 'decimal', 'name' => 'заработок', 'min' => 0, 'nullable' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'franchisee' => array(
            'name' => array('type' => '', 'name' => 'имя', 'max_length' => 90, 'min_length' => 1, 'nullable' => true, 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'customer' => array(
            'name' => array('type' => 'string', 'name' => 'имя', 'max_length' => 150, 'min_length' => 1, 'nullable' => false, 'viewed' => true),
            'phone' => array('type' => 'string', 'name' => 'телефон', 'min' => 0, 'nullable' => false),
            'points' => array('type' => 'decimal', 'name' => 'кол-о заказов', 'min' => 0, 'nullable' => true),
            'amount' => array('type' => 'decimal', 'name' => 'сумма покупок', 'min' => 0, 'nullable' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'contact' => array(        
            'firstname' => array('type' => 'string', 'max_length' => 90, 'min_length' => 1, 'name' => 'имя'),
            'lastname' => array('type' => 'string', 'max_length' => 90, 'min_length' => 0, 'name' => 'фамилия', 'nullable' => true),
            'middlename' => array('type' => 'string', 'max_length' => 90, 'min_length' => 0, 'name' => 'отчество', 'nullable' => true),
            'login' => array('type' => 'string', 'max_length' => 90, 'min_length' => 0, 'name' => 'Логин', 'nullable' => true),
            'password' => array('type' => 'password', 'max_length' => 90, 'min_length' => 0, 'name' => 'Пароль', 'nullable' => true),
        ),
        'set' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'offer' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'motivation' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'profit_type' => array('type' => 'config', 'config' => 'motivation_profit_type', 'code' => 'profit_type', 'name' => 'вознаграждение'),
            'profit_value' => array('type' => 'decimal', 'code' => 'profit_value', 'min' => 0, 'name' => 'размер вознаграждения', 'hint' => array(
                'Цель - Оборот: размер вознаграждения - это дополнительный процент поверх уровня бариста.',
                'Цель - Товары: размер вознаграждения - процент от оборота товаров.',
            )),
            'condition_type' => array('type' => 'config', 'config' => 'motivation_condition_type', 'code' => 'condition_type', 'name' => 'тип мотивации'),
            'condition_value' => array('type' => 'decimal', 'code' => 'condition_value', 'min' => 0, 'step' => 0.01, 'name' => 'цель', 'hint' => 'Не учитывается при типе мотивации "Товар"'),
            'description' => array('type' => 'text', 'code' => 'description', 'max_length' => 5000, 'min_length' => 50, 'name' => 'описание'),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'screen' => array(
            'sort' => array('type' => 'sort', 'name' => '', 'nullable' => true, 'viewed' => true),
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'sku' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название артикула'),
            'sku' => array('type' => 'string', 'max_length' => 50, 'min_length' => 4, 'regexp' => '/[^A-Za-z0-9]/', 'name' => 'код артикула'),
            'price' => array('type' => 'decimal', 'min' => 0.01, 'name' => 'цена артикула', 'step' => 0.01),
        ),
        'shop' => array(
            'name' => array('type' => 'string', 'max_length' => 100, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'address' => array('type' => 'string', 'max_length' => 200, 'min_length' => 6, 'name' => 'адрес'),
            'code' => array('type' => 'string', 'max_length' => 50, 'min_length' => 4, 'regexp' => '/[^A-Za-z0-9]/', 'name' => 'код', 'hint' => 'Код может содержать только латинские буквы и цифры', 'viewed' => true),
            'rent' => array('type' => 'decimal', 'min' => 0.01, 'name' => 'арендная плата', 'step' => 0.01, 'viewed' => true),
            'terminal_mac' => array('type' => 'string', 'max_length' => 20, 'min_length' => 8, 'regexp' => '/[^A-Za-z0-9]/', 'name' => 'мac-адрес терминала', 'viewed' => true),
            'info_mac' => array('type' => 'string', 'max_length' => 20, 'min_length' => 8, 'regexp' => '/[^A-Za-z0-9]/', 'name' => 'мac-адрес кассы'),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'stock' => array(
            'name' => array('type' => 'string', 'max_length' => 100, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'address' => array('type' => 'string', 'max_length' => 200, 'min_length' => 6, 'name' => 'адрес'),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'supply' => array(
            'id' => array('name' => 'поставка', 'viewed' => true),
            'shop_name' => array('name' => 'точка', 'viewed' => true),
            'supplier_name' => array('name' => 'поставщик', 'viewed' => true),
            'shop_id' => array('type' => 'select-two', 'code' => 'shop_id', 'action' => '?module=backend&action=selectTwo&class=shop', 'name' => 'точка'),
            'supplier_id' => array('type' => 'select-two', 'code' => 'supplier_id', 'action' => '?module=backend&action=selectTwo&class=supplier', 'name' => 'поставщик'),
            'planed_date' => array('type' => 'date', 'code' => 'planed_date', 'name' => 'предположительбное время поставки', 'format' => 'yy.mm.dd'),
            'date_time' => array('type' => 'time', 'code' => 'date_time', 'name' => 'время приёма поставки', 'format' => 'HH:mm:ss', 'nullable' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'supplyItems' => array(
            'count' => array('type' => 'decimal', 'code' => 'count', 'min' => 0, 'name' => 'остаток', 'step' => 0.01, 'viewed' => true),
            'start_count' => array('type' => 'decimal', 'code' => 'start_count', 'min' => 0, 'name' => 'количество', 'step' => 0.01, 'viewed' => true),
            'unit' => array('type' => 'config', 'code' => 'unit', 'second_depth' => true, 'name' => 'единица измерения'),
        ),
        'supplier' => array(
            'name' => array('type' => 'string', 'max_length' => 100, 'min_length' => 4, 'name' => 'название', 'unique' => 'используется введённое название', 'viewed' => true),
            'contact_name' => array('type' => 'string', 'max_length' => 100, 'min_length' => 4, 'name' => 'контактоное лицо', 'viewed' => true),
            'supply_time' => array('type' => 'time', 'name' => 'время поставок', 'format' => 'HH:mm:ss'),
            'access_key' => array('type' => 'string', 'max_length' => 50, 'min_length' => 4, 'regexp' => '/[^A-Za-z0-9]/', 'name' => 'код доступа', 'unique' => 'используется введённый код доступа'),
            'inn' => array('type' => 'string', 'max_length' => 20, 'min_length' => 8, 'name' => 'ИНН', 'regexp' => '/[^0-9]/', 'unique' => 'используется введённый ИНН'),
            'planned_date' => array('type' => 'date', 'name' => 'дата поставок', 'format' => 'yy.mm.dd'),
            'email_notification' => array('type' => 'checkbox', 'name' => 'рассылка на почту', 'nullable' => true),
            'phone_notification' => array('type' => 'checkbox', 'name' => 'sms рассылка', 'nullable' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
        'supplierIngredients' => array(
            'min_purchase' => array('type' => 'decimal', 'code' => 'min_purchase', 'min' => 0, 'name' => 'минимальная поставка', 'step' => 0.01, 'viewed' => true),
            'unit' => array('type' => 'config', 'code' => 'unit', 'second_depth' => true, 'name' => 'единица измерения'),
            'discrete' => array('type' => 'checkbox', 'code' => 'discrete', 'name' => 'дискретная поставка', 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус', 'viewed' => true),
        ),
        'ingredientCategory' => array(
            'name' => array('type' => 'string', 'max_length' => 90, 'min_length' => 4, 'name' => 'название', 'viewed' => true),
            'status' => array('type' => 'config', 'code' => 'status', 'name' => 'статус'),
        ),
    ),
    'status' => array(
        1 => array('id' => 1, 'name' => 'Активен', 'code' => 'active'),
        2 => array('id' => 2, 'name' => 'Модерация', 'code' => 'moderation'),
        0 => array('id' => 0, 'name' => 'Удален', 'code' => 'delete'),
    ),
    'dimension' => array(
        1 => array('id' => 1, 'name' => 'объем', 'code' => 'volume'),
        2 => array('id' => 2, 'name' => 'вес', 'code' => 'weight'),
        3 => array('id' => 3, 'name' => 'кол-во', 'code' => 'count'),
    ),
    'unit' => array(
        'volume' => array(1 => array('name' => 'литр'), 2 => array('name' => 'мл.'),),
        'weight' => array(3 => array('name' => 'кг.'), 4 => array('name' => 'гр.'),),
        'count' => array(5 => array('name' => 'шт.'),),
    ),
    'contact_types' => array(
        1 => array('id' => 1, 'name' => 'Администратор', 'code' => 'admin'),
        2 => array('id' => 2, 'name' => 'Франчайзи', 'code' => 'franchise'),
        3 => array('id' => 3, 'name' => 'Работник', 'code' => 'worker'),
        4 => array('id' => 4, 'name' => 'Покупатель', 'code' => 'customer'),
    ),
    'menu' => array(
        array(
            'title' => 'Основные данные',
            'icon' => 'ribbon',
            'children' => array(
                array('title' => 'Главная', 'module' => 'backend',),
                array('title' => 'Список точек', 'module' => 'shop'),
                array('title' => 'Мотивации', 'module' => 'motivation',),
                array('title' => 'Акции', 'module' => 'offer',),
                array('title' => 'Заказы', 'module' => 'order',),
                array('title' => 'Отчёты', 'module' => 'report',),
            ),
        ),
        array(
            'title' => 'Пользователи',
            'icon' => 'customer',
            'children' => array(
                array('title' => 'Работники', 'module' => 'worker',),
                array('title' => 'Франчайзи', 'module' => 'franchisee',),
                array('title' => 'Гости', 'module' => 'customer',),
            ),
        ),
        array(
            'title' => 'Товарная матрица',
            'icon' => 'coupon',
            'children' => array(
                array('title' => 'Ингредиенты', 'module' => 'ingredient',),
                array('title' => 'Категории ингредиентов', 'module' => 'ingredient', 'action' => 'category',),
                array('title' => 'Товары', 'module' => 'product',),
                array('title' => 'Дополнения', 'module' => 'addition',),
                array('title' => 'Списки товаров', 'module' => 'set',),
            ),
        ),
        array(
            'title' => 'Система складов',
            'icon' => 'box',
            'children' => array(
                array('title' => 'Склады', 'module' => 'stock',),
                array('title' => 'Поставщики', 'module' => 'supplier',),
                array('title' => 'Поставки', 'module' => 'supply',),
                array('title' => 'Инвентаризация', 'module' => 'inventory',),
            ),
        ),
        array(
            'title' => 'Настройки',
            'icon' => 'settings',
            'children' => array(
                array('title' => 'Меню', 'module' => 'screen',),
                array('title' => 'Настройки', 'module' => 'settings',),
            ),
        ),
    ),
    'screen_type' => array(
        0 => array('name' => 'Пустой элемент', 'code' => 'void'),
        1 => array('name' => 'Заголовок', 'code' => 'title'),
        2 => array('name' => 'Подменю', 'code' => 'menu'),
        3 => array('name' => 'Товар', 'code' => 'product'),
    ),
    'product_type' => array(
        1 => array('id' => 1, 'name' => 'Товар', 'code' => 'product'),
        2 => array('id' => 2, 'name' => 'Дополнение', 'code' => 'addition'),
    ),
    'payment_type' => array(
        1 => array('id' => 1, 'name' => 'Наличными', 'code' => 'cash'),
        2 => array('id' => 2, 'name' => 'Картой', 'code' => 'cart'),
    ),
    'entity_type' => array(
        1 => array('id' => 1, 'name' => 'Товар', 'code' => 'product'),
        2 => array('id' => 2, 'name' => 'Дополнение', 'code' => 'addition'),
        3 => array('id' => 3, 'name' => 'Список', 'code' => 'set'),
        4 => array('id' => 4, 'name' => 'Арикул', 'code' => 'sku'),
    ),
    'offer_time' => array(
        1 => array('name' => 'Никогда', 'code' => 'never',),
        2 => array('name' => 'Всегда', 'code' => 'always',),
        3 => array('name' => 'По дням недели', 'code' => 'weekdays', 'values' => array(
            0 => 'Понедельник', 1 => 'Вторник', 2 => 'Среда', 3 => 'Четверг', 4 => 'Пятница', 5 => 'Суббота', 6 => 'Воскресенье',
        )),
        4 => array('name' => 'Точные даты', 'code' => 'dates',),
    ),
    'offer_condition' => array(
        1 => array('name' => 'Вручную', 'code' => 'manual',),
        2 => array('name' => 'По составу товаров', 'code' => 'products',),
        3 => array('name' => 'По группе клиента', 'code' => 'category',),
    ),
    'offer_condition_type' => array(
        1 => array('name' => 'Продукт', 'code' => 'product',),
        2 => array('name' => 'Список товаров', 'code' => 'set',)
    ),
    'offer_profit' => array(
        1 => array('name' => 'Весь заказ', 'code' => 'all',),
        2 => array('name' => 'Определенные товары', 'code' => 'certain'),
    ),
    'offer_profit_type' => array(
        1 => array('name' => 'Скидка в процентах - только товар', 'code' => 'percent_product'),
        2 => array('name' => 'Скидка в процентах - товар и дополнения', 'code' => 'percent_all'),
        3 => array('name' => 'Скидка в рублях', 'code' => 'rub'),
        4 => array('name' => 'Установить цену', 'code' => 'set_price')
    ),
    'motivation_profit_type' => array(
        1 => array('name' => 'Рубли'),
        2 => array('name' => 'Проценты от оборота'),
    ),
    'inventory_type' => array(
        1 => array('name' => 'Короткая'),
        2 => array('name' => 'Полная'),
    ),
    'motivation_condition_type' => array(
        1 => array('id' => 1, 'name' => 'Оборот', 'code' => 'turnover',),
        2 => array('id' => 2, 'name' => 'Оборот за день', 'code' => 'day_turnover',),
        3 => array('id' => 3, 'name' => 'Товары', 'code' => 'product',),
        4 => array('id' => 4, 'name' => 'Средний чек за день', 'code' => 'day_avg_check',),
        5 => array('id' => 5, 'name' => 'Средний чек за месяц', 'code' => 'month_avg_check',),
        6 => array('id' => 6, 'name' => 'Заказов за день', 'code' => 'day_order_total',),
        7 => array('id' => 7, 'name' => 'Заказов за месяц', 'code' => 'month_order_total',),
    ),
    'motivation_timing_type' => array(
        1 => array('name' => 'Никогда', 'code' => 'never',),
        2 => array('name' => 'Всегда', 'code' => 'always',),
        3 => array('name' => 'По дням недели', 'code' => 'weekdays', 'values' => array(
            0 => 'Понедельник', 1 => 'Вторник', 2 => 'Среда', 3 => 'Четверг', 4 => 'Пятница', 5 => 'Суббота', 6 => 'Воскресенье',
        )),
        4 => array('name' => 'Точные даты', 'code' => 'dates',),
        5 => array('name' => 'Периоды', 'code' => 'periods',),
    )
);