<?php
return array(
    'rc_category_ingredients' => array(
        'category_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('category_id', 'ingredient_id'),
        ),
    ),
    'rc_customer' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11),
        'group_id' => array('int', 11),
        'name' => array('varchar', 255, 'null' => 0),
        'phone' => array('varchar', 20, 'null' => 0),
        'amount' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'points' => array('int', 11, 'null' => 0, 'default' => '0'),
        'status' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'name_phone' => array('name', 'phone', 'fulltext' => 1),
        ),
    ),
    'rc_customer_hystory' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'field' => array('int', 11, 'null' => 0),
        'value' => array('decimal', "15,4"),
        'before_value' => array('varchar', 256, 'null' => 0),
        'after_value' => array('varchar', 256, 'null' => 0),
        'description' => array('text', 'null' => 0),
        'customer_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'order_id' => array('int', 11),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'customer_id' => 'customer_id',
            'contact_id' => 'contact_id',
            'order_id' => 'order_id',
        ),
    ),
    'rc_franchisee' => array(
        'contact_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11),
        'status' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'contact_id',
        ),
    ),
    'rc_ingredient' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'code' => array('varchar', 64, 'null' => 0),
        'price' => array('double', "15,4", 'null' => 0),
        'dimension' => array('int', 11, 'null' => 0),
        'calories' => array('decimal', "15,4", 'null' => 0),
        'proteins' => array('decimal', "15,4", 'null' => 0),
        'fats' => array('decimal', "15,4", 'null' => 0),
        'carbohydrates' => array('decimal', "15,4", 'null' => 0),
        'status' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_ingredient_category' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 255, 'null' => 0),
        'status' => array('int', 11, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_inventory' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        'edit_date_time' => array('datetime', 'null' => 0),
        'comment' => array('text', 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_id' => array('shop_id', 'type', 'contact_id'),
        ),
    ),
    'rc_inventory_dates' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11, 'null' => 0),
        'month' => array('int', 11, 'null' => 0),
        'day' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_id' => 'shop_id',
        ),
    ),
    'rc_inventory_items' => array(
        'inventory_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'count' => array('decimal', "15,4", 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('inventory_id', 'ingredient_id'),
        ),
    ),
    'rc_log' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'type_id' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11, 'null' => 0),
        'description' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'id_UNIQUE' => array('id', 'unique' => 1),
            'contact_id' => 'contact_id',
            'entity_id' => 'entity_id',
        ),
    ),
    'rc_log_category_ingredients' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'category_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_customer' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'customer_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_franchisee' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'franchisee_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_ingredient' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'ingredient_id' => 'ingredient_id',
            'action_id' => 'action_id',
        ),
    ),
    'rc_log_ingredient_category' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'category_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_motivation' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'motivation_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text', 'null' => 0),
        'data_after' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'product_id' => 'motivation_id',
            'action_id' => 'action_id',
        ),
    ),
    'rc_log_motivation_dates' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'motivation_id' => array('int', 11, 'null' => 0),
        'month_day' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_motivation_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'motivation_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'entity_id' => array('varchar', 45, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'quantity_before' => array('int', 11),
        'quantity_after' => array('int', 11),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_motivation_period' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'motivation_id' => array('int', 11, 'null' => 0),
        'motivation_period_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_motivation_weekdays' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'motivation_id' => array('int', 11, 'null' => 0),
        'day_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_offer' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'offer_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'product_id' => 'offer_id',
            'action_id' => 'action_id',
        ),
    ),
    'rc_log_offer_condition_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'offer_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11, 'null' => 0),
        'quantity_before' => array('int', 11, 'default' => '0'),
        'quantity_after' => array('int', 11, 'default' => '0'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_offer_contact_group' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'offer_id' => array('int', 11, 'null' => 0),
        'group_id' => array('int', 11, 'null' => 0),
        'date_time' => array('varchar', 45, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_offer_dates' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'offer_id' => array('int', 11, 'null' => 0),
        'day' => array('int', 11, 'null' => 0),
        'month' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_offer_exceptions' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'offer_id' => array('int', 11, 'null' => 0),
        'offer_exception_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_offer_profit_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'offer_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_offer_weekdays' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'offer_id' => array('int', 11, 'null' => 0),
        'day_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_product' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'product_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text', 'null' => 0),
        'data_after' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'product_id' => 'product_id',
            'action_id' => 'action_id',
        ),
    ),
    'rc_log_product_additions' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'product_addition_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'status_before' => array('int', 11, 'null' => 0, 'default' => '0'),
        'status_after' => array('int', 11, 'null' => 0, 'default' => '1'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_product_ingredients' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'product_id' => array('int', 11, 'null' => 0),
        'sku_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_product_sku' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'sku_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'default' => '0'),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_screen' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'screen_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text', 'null' => 0),
        'data_after' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'screen_id' => 'screen_id',
            'action_id' => 'action_id',
        ),
    ),
    'rc_log_set' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'set_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_settings' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'code' => array('varchar', 255, 'null' => 0),
        'value_before' => array('text'),
        'value_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_shop' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text', 'null' => 0),
        'data_after' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'contact_id',
            'shop_id' => 'shop_id',
            'action_id' => 'action_id',
        ),
    ),
    'rc_log_shop_franchisees' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'franchisee_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_shop_motivations' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11, 'null' => 0),
        'motivation_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_shop_offers' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        'offer_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_supplier' => array(
        'id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'supplier_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('id', 'date_time'),
        ),
    ),
    'rc_log_supplier_ingredients' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'supplier_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'field' => array('varchar', 45, 'null' => 0),
        'value_before' => array('varchar', 256),
        'value_after' => array('varchar', 256),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_log_worker' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'action_id' => array('int', 11, 'null' => 0),
        'worker_id' => array('int', 11, 'null' => 0),
        'data_before' => array('text'),
        'data_after' => array('text'),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_motivation' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'description' => array('text', 'null' => 0),
        'profit_type' => array('int', 11),
        'profit_value' => array('decimal', "15,4"),
        'condition_type' => array('int', 11),
        'condition_value' => array('decimal', "15,4", 'default' => '0.0000'),
        'timing_type' => array('int', 11),
        'total' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'count' => array('int', 11, 'null' => 0, 'default' => '0'),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_motivation_dates' => array(
        'motivation_id' => array('int', 11, 'null' => 0),
        'month_day' => array('int', 11, 'null' => 0),
        'start_time' => array('time', 'null' => 0),
        'end_time' => array('time', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('motivation_id', 'month_day'),
            'motivation_id' => 'motivation_id',
        ),
    ),
    'rc_motivation_items' => array(
        'motivation_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11, 'null' => 0),
        'quantity' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('motivation_id', 'type', 'entity_id'),
            'motivation_id' => array('motivation_id', 'entity_id', 'unique' => 1),
        ),
    ),
    'rc_motivation_period' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'motivation_id' => array('int', 11, 'null' => 0),
        'start_date' => array('date', 'null' => 0),
        'end_date' => array('date', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'motivation_id' => 'motivation_id',
        ),
    ),
    'rc_motivation_weekdays' => array(
        'motivation_id' => array('int', 11, 'null' => 0),
        'day_id' => array('int', 11, 'null' => 0),
        'start_time' => array('time', 'null' => 0),
        'end_time' => array('time', 'null' => 0),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => array('motivation_id', 'day_id'),
            'motivation_id' => 'motivation_id',
        ),
    ),
    'rc_offer' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'product_selection' => array('int', 11),
        'timing_type' => array('int', 11, 'null' => 0, 'default' => '0'),
        'condition_type' => array('int', 11, 'null' => 0, 'default' => '0'),
        'profit_type' => array('int', 11, 'null' => 0, 'default' => '0'),
        'discount' => array('int', 11, 'default' => '0'),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_offer_condition_items' => array(
        'offer_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11, 'null' => 0),
        'quantity' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('offer_id', 'type', 'entity_id'),
        ),
    ),
    'rc_offer_contact_group' => array(
        'offer_id' => array('int', 11, 'null' => 0),
        'group_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('offer_id', 'group_id'),
        ),
    ),
    'rc_offer_dates' => array(
        'offer_id' => array('int', 11, 'null' => 0),
        'month' => array('int', 11, 'null' => 0),
        'day' => array('int', 11, 'null' => 0),
        'start_time' => array('time', 'null' => 0),
        'end_time' => array('time', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('offer_id', 'month', 'day'),
        ),
    ),
    'rc_offer_exceptions' => array(
        'offer_id' => array('int', 11, 'null' => 0),
        'offer_exception_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('offer_id', 'offer_exception_id'),
        ),
    ),
    'rc_offer_profit_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'offer_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11, 'null' => 0),
        'quantity' => array('int', 11, 'null' => 0),
        'profit_type' => array('int', 11),
        'profit_value' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_offer_weekdays' => array(
        'offer_id' => array('int', 11, 'null' => 0),
        'day_id' => array('int', 11, 'null' => 0),
        'start_time' => array('time'),
        'end_time' => array('time'),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => array('offer_id', 'day_id'),
        ),
    ),
    'rc_order' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11),
        'payment_type' => array('int', 11),
        'price' => array('decimal', "15,4"),
        'discount' => array('decimal', "15,4"),
        'purchase' => array('decimal', "15,4"),
        'date_time' => array('datetime'),
        'cash_box_id' => array('int', 11),
        'customer_id' => array('int', 11),
        'status' => array('int', 11),
        ':keys' => array(
            'PRIMARY' => 'id',
            'contact_id' => 'customer_id',
        ),
    ),
    'rc_order_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'order_id' => array('int', 11, 'null' => 0),
        'product_id' => array('int', 11, 'null' => 0),
        'sku_id' => array('int', 11, 'null' => 0),
        'parent_id' => array('int', 11),
        'count' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 180, 'null' => 0),
        'price' => array('decimal', "15,4", 'null' => 0),
        'discount' => array('decimal', "15,4", 'null' => 0),
        'purchase' => array('decimal', "15,4", 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_order_workers' => array(
        'order_id' => array('int', 11, 'null' => 0),
        'worker_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('order_id', 'worker_id'),
        ),
    ),
    'rc_page' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'parent_id' => array('int', 11),
        'domain' => array('varchar', 255),
        'route' => array('varchar', 255),
        'name' => array('varchar', 255, 'null' => 0),
        'title' => array('varchar', 255, 'null' => 0, 'default' => ''),
        'url' => array('varchar', 255),
        'full_url' => array('varchar', 255),
        'content' => array('text', 'null' => 0),
        'create_datetime' => array('datetime', 'null' => 0),
        'update_datetime' => array('datetime', 'null' => 0),
        'create_contact_id' => array('int', 11, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'status' => array('tinyint', 1, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'routing' => array('route', 'status'),
        ),
    ),
    'rc_page_params' => array(
        'page_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 255, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('page_id', 'name'),
        ),
    ),
    'rc_product' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'price' => array('decimal', "15,4", 'default' => '0.0000'),
        'type' => array('int', 11, 'null' => 0),
        'status' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'sku_id' => 'price',
        ),
    ),
    'rc_product_additions' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'product_id' => array('int', 11, 'null' => 0),
        'addition_id' => array('int', 11, 'null' => 0),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'product_id' => array('product_id', 'addition_id'),
        ),
    ),
    'rc_product_ingredient' => array(
        'product_id' => array('int', 11, 'null' => 0),
        'sku_id' => array('int', 11, 'null' => 0, 'default' => '0'),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'amount' => array('decimal', "15,4", 'default' => '0.0000'),
        'unit' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('product_id', 'sku_id', 'ingredient_id'),
        ),
    ),
    'rc_product_set' => array(
        'product_id' => array('int', 11, 'null' => 0),
        'set_id' => array('int', 11, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('product_id', 'set_id'),
        ),
    ),
    'rc_product_sku' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'product_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 256, 'null' => 0, 'default' => ''),
        'sku' => array('varchar', 64, 'null' => 0),
        'price' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'product_id' => 'product_id',
        ),
    ),
    'rc_screen' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_screen_element' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'screen_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 256, 'null' => 0),
        'price' => array('decimal', "15,4"),
        'width' => array('int', 11, 'null' => 0),
        'height' => array('int', 11, 'null' => 0),
        'entity_id' => array('int', 11),
        'type' => array('int', 11, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_session' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'code' => array('varchar', 256, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_id' => 'shop_id',
        ),
    ),
    'rc_session_workers' => array(
        'session_id' => array('int', 11, 'null' => 0),
        'worker_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('session_id', 'worker_id'),
        ),
    ),
    'rc_set' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_settings' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'code' => array('varchar', 225, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_shop' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'address' => array('varchar', 1000, 'null' => 0),
        'code' => array('varchar', 20, 'null' => 0),
        'rent' => array('decimal', "15,4", 'null' => 0),
        'latitude' => array('decimal', "18,15"),
        'longitude' => array('decimal', "18,15"),
        'salt' => array('varchar', 255, 'null' => 0),
        'terminal_mac' => array('varchar', 64, 'null' => 0),
        'info_mac' => array('varchar', 64, 'null' => 0),
        'status' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_shop_expence' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'amount' => array('decimal', "15,4", 'null' => 0),
        'comment' => array('text', 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'expence_category_id' => array('int', 11, 'null' => 0),
        'status' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_id' => array('shop_id', 'type', 'contact_id', 'expence_category_id'),
        ),
    ),
    'rc_shop_franchisees' => array(
        'shop_id' => array('int', 11, 'null' => 0),
        'franchisee_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('shop_id', 'franchisee_id'),
        ),
    ),
    'rc_shop_motivations' => array(
        'shop_id' => array('int', 11, 'null' => 0),
        'motivation_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('shop_id', 'motivation_id'),
        ),
    ),
    'rc_shop_offers' => array(
        'offer_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('offer_id', 'shop_id'),
        ),
    ),
    'rc_shop_product_additions' => array(
        'product_adition_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        'price' => array('decimal', "15,4", 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('product_adition_id', 'shop_id'),
        ),
    ),
    'rc_shop_settings' => array(
        'shop_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 50, 'null' => 0),
        'value' => array('text', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('shop_id', 'name'),
        ),
    ),
    'rc_shop_statistic' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11, 'null' => 0),
        'date' => array('date', 'null' => 0),
        'order_count' => array('int', 11, 'null' => 0, 'default' => '0'),
        'avg_check' => array('decimal', "15,4", 'default' => '0.0000'),
        'sales' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'cost_price' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'discounts' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'rent' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'salary' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'interest_rate' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'motivation' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'write_off' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'profit' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_id' => 'shop_id',
        ),
    ),
    'rc_shop_suppliers' => array(
        'shop_id' => array('int', 11, 'null' => 0),
        'supplier_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('shop_id', 'supplier_id'),
        ),
    ),
    'rc_shop_timetable' => array(
        'shop_id' => array('int', 11, 'null' => 0),
        'day_id' => array('int', 11, 'null' => 0),
        'start_time' => array('datetime', 'null' => 0),
        'end_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('shop_id', 'day_id'),
        ),
    ),
    'rc_shop_workers' => array(
        'shop_id' => array('int', 11, 'null' => 0),
        'worker_id' => array('int', 11, 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('shop_id', 'worker_id'),
        ),
    ),
    'rc_supplier' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'name' => array('varchar', 256, 'null' => 0),
        'contact_name' => array('varchar', 256, 'null' => 0),
        'supply_time' => array('time'),
        'access_key' => array('varchar', 256, 'null' => 0),
        'inn' => array('varchar', 50, 'null' => 0),
        'planned_date' => array('date'),
        'email_notification' => array('int', 11, 'default' => '0'),
        'phone_notification' => array('int', 11, 'default' => '0'),
        'send_all' => array('int', 11, 'default' => '0'),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'id',
        ),
    ),
    'rc_supplier_ingredients' => array(
        'supplier_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'min_purchase' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'unit' => array('int', 11),
        'discrete' => array('int', 11, 'null' => 0, 'default' => '0'),
        'status' => array('int', 11, 'null' => 0, 'default' => '0'),
        ':keys' => array(
            'PRIMARY' => array('supplier_id', 'ingredient_id'),
        ),
    ),
    'rc_supply' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'shop_id' => array('int', 11, 'null' => 0),
        'shop_entity_id' => array('int', 11),
        'supplier_id' => array('int', 11, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'planed_date' => array('date', 'null' => 0),
        'date_time' => array('datetime'),
        'status' => array('int', 11, 'default' => '2'),
        ':keys' => array(
            'PRIMARY' => 'id',
            'shop_id' => 'shop_id',
            'supplier_id' => 'supplier_id',
            'contact_id' => 'contact_id',
        ),
    ),
    'rc_supply_items' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'supply_id' => array('int', 11, 'null' => 0),
        'ingredient_id' => array('int', 11, 'null' => 0),
        'count' => array('decimal', "15,4", 'default' => '0.0000'),
        'dimension' => array('int', 11, 'null' => 0),
        'unit' => array('int', 11, 'null' => 0),
        'start_count' => array('decimal', "15,4", 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'supply_id' => array('supply_id', 'ingredient_id'),
        ),
    ),
    'rc_supply_items_history' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'supply_item_id' => array('int', 11, 'null' => 0),
        'before_value' => array('varchar', 64, 'null' => 0),
        'after_value' => array('varchar', 64, 'null' => 0),
        'contact_id' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'supply_item_id' => 'supply_item_id',
            'contact_id' => 'contact_id',
        ),
    ),
    'rc_worker' => array(
        'contact_id' => array('int', 11, 'null' => 0),
        'salary' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'hour_payment' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'interest_rate' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'amount' => array('decimal', "15,4", 'null' => 0, 'default' => '0.0000'),
        'status' => array('int', 11, 'null' => 0, 'default' => '1'),
        ':keys' => array(
            'PRIMARY' => 'contact_id',
        ),
    ),
    'rc_worker_activity' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'worker_id' => array('int', 11, 'null' => 0),
        'shop_id' => array('int', 11, 'null' => 0),
        'type' => array('int', 11, 'null' => 0),
        'date_time' => array('datetime', 'null' => 0),
        ':keys' => array(
            'PRIMARY' => 'id',
            'worker_id' => array('worker_id', 'shop_id'),
        ),
    ),
    'rc_worker_motivation' => array(
        'worker_id' => array('int', 11, 'null' => 0),
        'motivation_id' => array('int', 11, 'null' => 0),
        'total' => array('decimal', "15,4", 'null' => 0),
        'percent' => array('decimal', "15,4", 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('worker_id', 'motivation_id'),
        ),
    ),
    'rc_worker_motivation_items' => array(
        'worker_id' => array('int', 11, 'null' => 0),
        'motivation_item_id' => array('int', 11, 'null' => 0),
        'quantity' => array('int', 11, 'null' => 0),
        'percent' => array('decimal', "15,4", 'null' => 0),
        ':keys' => array(
            'PRIMARY' => array('worker_id', 'motivation_item_id'),
        ),
    ),
);
